LinkLuaModifier( "modifier_player_ability_checker", "modifiers/players/modifier_player_ability_checker", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_generic_collect_stats", "modifiers/players/modifier_generic_collect_stats", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_dawnbreaker_starbreaker_effect_only", "modifiers/heroes/dawnbreaker/modifier_dawnbreaker_starbreaker_effect_only", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_z_delta_visual", "modifiers/modifier_z_delta_visual", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_model_scale_ad_2023", "modifiers/modifier_model_scale_ad_2023", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_fix_death_units_crash_modifiers", "modifiers/modifier_fix_death_units_crash_modifiers", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_unslowable_2023", "modifiers/modifier_unslowable_2023", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_model_change_visual", "modifiers/modifier_model_change_visual", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_strong_illusion_hoodwink_ult", "modifiers/illusion/modifier_strong_illusion_hoodwink_ult", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_provides_vision_strong", "modifiers/modifier_provides_vision_strong", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_dummy_unit_map_icon", "modifiers/modifier_dummy_unit_map_icon", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_ability_value_upgrades_sb_2023", "modifiers/special_upgrades/modifier_ability_value_upgrades_sb_2023", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier( "modifier_spirit_bear_upgrades_ad_2023", "modifiers/heroes/lone_druid/modifier_spirit_bear_upgrades_ad_2023", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier( "modifier_summoned_unit_bat_upgrade_ad_2023", "modifiers/special_upgrades/modifier_summoned_unit_bat_upgrade_ad_2023", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier( "modifier_hero_ability_modified_ad_2023", "modifiers/special_upgrades/modifier_hero_ability_modified_ad_2023", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier( "modifier_fake_ally_ad_2023", "modifiers/modifier_fake_ally_ad_2023", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier( "modifier_cosmetic_inventory_sb2023", "modifiers/cosmetic_inventory/modifier_cosmetic_inventory_sb2023", LUA_MODIFIER_MOTION_NONE )

--supporters modifiers
LinkLuaModifier( "modifier_dummy_unit_supporters_sb_2023", "modifiers/supporters/modifier_dummy_unit_supporters_sb_2023", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_custom_head_mask_sb_2023", "modifiers/cosmetic_inventory/modifier_custom_head_mask_sb_2023", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_lc_fallen_legion_cosmetic_activity", "modifiers/cosmetic_inventory/modifier_lc_fallen_legion_cosmetic_activity", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_sven_ti7_sword_status_effect_custom", "modifiers/cosmetic_inventory/modifier_sven_ti7_sword_status_effect_custom", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_axe_unleash_model_sb_2023", "modifiers/cosmetic_inventory/modifier_axe_unleash_model_sb_2023", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_cosmetic_wearable_model_change", "modifiers/cosmetic_inventory/modifier_cosmetic_wearable_model_change", LUA_MODIFIER_MOTION_NONE )